version: '3'
services:
    web: &web
        #build: .
        image: nebojsatomic/5.6-apache-rw-mysqli:1.0
        #image: php:5.6-apache
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './src:/var/www/html'
        networks:
            - cmside2
        depends_on:
            - mysqldb
    mysqldb:
        image: 'mysql:5.6'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'nebojsa'
            MYSQL_DATABASE: 'cms_ide'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'nebojsa'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './data:/var/lib/mysql'
        networks:
            - cmside2
networks:
    cmside2:
        driver: bridge
#volumes:
#    cmsidemysql:
#        driver: local
