version: '3'
services:
    web: &web
        #build: .
        image: registry.gitlab.com/nebojsatomic/ide21:1.2
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - 'ide21src:/var/www/html'
        #user: ${CURRENT_UID}
        networks:
            - cmside2
        depends_on:
            - mysqldb
    mysqldb:
        #image: 'mysql:5.6'
        image: 'mariadb:10.9.3'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'nebojsa'
            MYSQL_DATABASE: 'cms_ide'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'nebojsa'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './data:/var/lib/mysql'
        networks:
            - cmside2
networks:
    cmside2:
        driver: bridge
volumes:
    ide21src:
        driver: local
